version: "3.3"

services:
  mysql-db:
    image: mysql:8.0
    container_name: mysqldb
    environment:
     MYSQL_DATABASE: librarydb
     MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./db/librarydb.sql:/docker-entrypoint-initdb.d/librarydb.sql
  app:
    build: .
    restart: always
    command: node dist/index.js
    container_name: app
    depends_on:
      - mysql-db
    ports:
      - "3000:3000"
    volumes:
      - ./server:/src
    links:
      - mysql-db